export const items = [
    {
        id: 1,
        title: "Anomalous login pattern detected from EU region",
        summary: "Multiple failed auth attempts followed by a successful login from an IP not associated with this user.",
        status: "new",
        priority: "critical",
        source: "auth-service",
        owner: "@sec-team",
        tags: ["security", "auth", "eu-region"],
        score: 0.94,
        createdAt: Date.now() - 2 * 60 * 1000
    },
    {
        id: 2,
        title: "Model output flagged for hallucination in legal document",
        summary: "Summariser produced a clause not in source document. Needs review.",
        status: "in-review",
        priority: "high",
        source: "ml-pipeline",
        owner: "@ml-team",
        tags: ["hallucination", "legal"],
        score: 0.88,
        createdAt: Date.now() - 14 * 60 * 1000
    },
    {
        id: 3,
        title: "Response truncated on mobile",
        summary: "Responses cut off around 800 characters on iOS.",
        status: "new",
        priority: "medium",
        source: "user-report",
        owner: "@alice",
        tags: ["bug", "mobile"],
        score: 0.61,
        createdAt: Date.now() - 31 * 60 * 1000
    },
    {
        id: 4,
        title: "Latency spike on inference cluster",
        summary: "P99 latency exceeded 4s for 11 minutes.",
        status: "resolved",
        priority: "low",
        source: "infra-alert",
        owner: "@platform",
        tags: ["infra", "latency"],
        score: 0.22,
        createdAt: Date.now() - 60 * 60 * 1000
    },
    {
        id: 5,
        title: "PII data detected in output",
        summary: "Pipeline emitting real email addresses.",
        status: "new",
        priority: "critical",
        source: "ml-pipeline",
        owner: null,
        tags: ["pii"],
        score: 0.91,
        createdAt: Date.now() - 2 * 60 * 60 * 1000
    },
    {
        id: 6,
        title: "Confidence score dropped",
        summary: "Confidence dropped below threshold.",
        status: "in-review",
        priority: "medium",
        source: "ml-pipeline",
        owner: "@ml-team",
        tags: ["confidence"],
        score: 0.55,
        createdAt: Date.now() - 3 * 60 * 60 * 1000
    },
    {
        id: 7,
        title: "API returning 429 errors",
        summary: "Rate limiting incorrectly applied.",
        status: "escalated",
        priority: "high",
        source: "api-gateway",
        owner: "@bob",
        tags: ["api"],
        score: 0.79,
        createdAt: Date.now() - 4 * 60 * 60 * 1000
    },
    {
        id: 8,
        title: "Broken privacy policy link",
        summary: "Signup flow link leads to 404.",
        status: "new",
        priority: "medium",
        source: "user-report",
        owner: "@alice",
        tags: ["bug", "ux"],
        score: 0.45,
        createdAt: Date.now() - 5 * 60 * 60 * 1000
    },
    {
        id: 9,
        title: "Model blocking valid chemistry questions",
        summary: "False positives in content filtering.",
        status: "new",
        priority: "medium",
        source: "user-report",
        owner: "@ml-team",
        tags: ["model"],
        score: 0.68,
        createdAt: Date.now() - 6 * 60 * 60 * 1000
    },
    {
        id: 10,
        title: "Token usage anomaly",
        summary: "Suspicious high usage detected.",
        status: "in-review",
        priority: "high",
        source: "auth-service",
        owner: "@sec-team",
        tags: ["security"],
        score: 0.83,
        createdAt: Date.now() - 7 * 60 * 60 * 1000
    },
    {
        id: 11,
        title: "Embedding model returns NaN",
        summary: "Emoji-only input causes failure.",
        status: "new",
        priority: "low",
        source: "ml-pipeline",
        owner: null,
        tags: ["bug"],
        score: 0.37,
        createdAt: Date.now() - 8 * 60 * 60 * 1000
    },
    {
        id: 12,
        title: "CSV export loses timezone",
        summary: "Timezone missing in exported data.",
        status: "new",
        priority: "medium",
        source: "user-report",
        owner: "@alice",
        tags: ["bug"],
        score: 0.50,
        createdAt: Date.now() - 9 * 60 * 60 * 1000
    },
    {
        id: 13,
        title: "Webhook failure for Slack",
        summary: "Messages not delivered.",
        status: "in-review",
        priority: "high",
        source: "api-gateway",
        owner: "@bob",
        tags: ["integration"],
        score: 0.74,
        createdAt: Date.now() - 10 * 60 * 60 * 1000
    },
    {
        id: 14,
        title: "Snooze bug",
        summary: "Items unsnoozed early.",
        status: "resolved",
        priority: "low",
        source: "infra-alert",
        owner: "@platform",
        tags: ["bug"],
        score: 0.20,
        createdAt: Date.now() - 12 * 60 * 60 * 1000
    },
    {
        id: 15,
        title: "Empty searches issue",
        summary: "Search queries firing unnecessarily.",
        status: "snoozed",
        priority: "low",
        source: "infra-alert",
        owner: "@platform",
        tags: ["search"],
        score: 0.31,
        createdAt: Date.now() - 14 * 60 * 60 * 1000
    },
    {
        id: 16,
        title: "GDPR deletion issue",
        summary: "Backup data not deleted.",
        status: "escalated",
        priority: "critical",
        source: "user-report",
        owner: "@sec-team",
        tags: ["privacy"],
        score: 0.96,
        createdAt: Date.now() - 16 * 60 * 60 * 1000
    },
    {
        id: 17,
        title: "Model memorization issue",
        summary: "Training data reproduced.",
        status: "in-review",
        priority: "critical",
        source: "ml-pipeline",
        owner: "@ml-team",
        tags: ["model"],
        score: 0.89,
        createdAt: Date.now() - 18 * 60 * 60 * 1000
    },
    {
        id: 18,
        title: "Keyboard overlap bug",
        summary: "Mobile keyboard hides input.",
        status: "new",
        priority: "medium",
        source: "user-report",
        owner: "@alice",
        tags: ["mobile"],
        score: 0.48,
        createdAt: Date.now() - 20 * 60 * 60 * 1000
    },
    {
        id: 19,
        title: "Search shows deleted data",
        summary: "Archived items still visible.",
        status: "new",
        priority: "high",
        source: "user-report",
        owner: "@bob",
        tags: ["search"],
        score: 0.77,
        createdAt: Date.now() - 22 * 60 * 60 * 1000
    },
    {
        id: 20,
        title: "Classifier inconsistency",
        summary: "Scores fluctuate unexpectedly.",
        status: "in-review",
        priority: "medium",
        source: "ml-pipeline",
        owner: "@ml-team",
        tags: ["model"],
        score: 0.58,
        createdAt: Date.now() - 24 * 60 * 60 * 1000
    },
    {
        id: 21,
        title: "SSO revoke not working",
        summary: "Feature returns 501 error.",
        status: "new",
        priority: "high",
        source: "user-report",
        owner: null,
        tags: ["auth"],
        score: 0.81,
        createdAt: Date.now() - 26 * 60 * 60 * 1000
    },
    {
        id: 22,
        title: "Long title UI break",
        summary: "Layout breaks for long titles.",
        status: "resolved",
        priority: "low",
        source: "user-report",
        owner: "@alice",
        tags: ["ui"],
        score: 0.18,
        createdAt: Date.now() - 28 * 60 * 60 * 1000
    },
    {
        id: 23,
        title: "Duplicate tags issue",
        summary: "Tags not deduplicated.",
        status: "resolved",
        priority: "low",
        source: "ml-pipeline",
        owner: "@platform",
        tags: ["bug"],
        score: 0.15,
        createdAt: Date.now() - 30 * 60 * 60 * 1000
    },
    {
        id: 24,
        title: "Sorting bug",
        summary: "Low score item appearing first.",
        status: "new",
        priority: "medium",
        source: "infra-alert",
        owner: "@platform",
        tags: ["bug"],
        score: 0.12,
        createdAt: Date.now() - 32 * 60 * 60 * 1000
    },
    {
        id: 25,
        title: "Empty state bug",
        summary: "Raw JSON shown instead of UI.",
        status: "new",
        priority: "medium",
        source: "infra-alert",
        owner: "@alice",
        tags: ["bug"],
        score: 0.42,
        createdAt: Date.now() - 34 * 60 * 60 * 1000
    }
];